"""The tile, top, and hint bars driven by domain coordinators."""

from collections.abc import Sequence
from typing import Protocol

from domain.catalog.window import Window
from domain.navigation.hints import Hints


class TileBarView(Protocol):
    """The tile bar shared by focus, move, pinning, and lifecycle coordinators."""

    def move(self, delta: int) -> bool: ...
    def select_current(self) -> None: ...
    def set_focused(self, focused: bool, scroll: bool = True) -> None: ...
    def current_is_add(self) -> bool: ...

    def app_tile_count(self) -> int: ...
    def current_app_index(self) -> int: ...
    def render_app_swap(self, i: int, j: int) -> None: ...
    def set_move_mode(self, active: bool) -> None: ...

    def set_static_closing(self, idx: int) -> None: ...
    def is_closing(self, idx: int) -> bool: ...
    def refresh_status(self) -> None: ...
    def has_dynamic_window(self, window_id: str) -> bool: ...
    def is_tile_running(self, idx: int, windows: Sequence[Window]) -> bool: ...


class TopBarView(Protocol):
    """The Home header shared by focus navigation and status updates."""

    @property
    def count(self) -> int: ...

    @property
    def default_index(self) -> int:
        """The initial focus index — Power rather than its row position."""
        ...

    def set_selected(self, index: int | None) -> None: ...
    def trigger(self, index: int) -> None: ...
    def has_menu_at(self, index: int) -> bool: ...

    def set_power_icon(self, icon: str) -> None: ...
    def set_network_icon(self, glyph: str) -> None: ...
    def set_notification_badge(self, count: int) -> None: ...


class HintBarView(Protocol):
    """The bottom hint bar shared by navigation and Home chrome."""

    def show_hints(self, hints: Hints) -> None: ...
    def show_at_bottom(self) -> None: ...
    def hide(self) -> None: ...
